<?php

namespace PN\DynamicFormBundle\Repository;

use PN\ServiceBundle\Utils\Validate;
use PN\ServiceBundle\Utils\SQL;
/**
 * SectionAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionAttributeRepository extends \Doctrine\ORM\EntityRepository {

    public function findBySection($sectionId) {
        return $this->findBy(["section" => $sectionId, "deleted" => null], ["sort" => "ASC"]);
    }

}
