<?php

namespace PN\DynamicFormBundle\Repository;

use PN\ServiceBundle\Utils\Validate;
use PN\ServiceBundle\Utils\SQL;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository {

    public function findAll() {
        return $this->findBy(["deleted" => null]);
    }

    public function findPrevious($sectionId) {
        $search = new \stdClass();
        $search->deleted = 0;
        $search->ordr = ["dir" => "ASC", "column" => 0];
        $search->previous = $sectionId;
        return $this->filter($search);
    }

    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL) {

        $sortSQL = [
            's.id',
            's.title',
        ];
        $connection = $this->getEntityManager()->getConnection();
        $where = FALSE;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) AND ! is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }
        if (isset($searchFiltered->deleted) AND in_array($searchFiltered->deleted, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            if ($searchFiltered->deleted == 1) {
                $clause .= $where . " s.deleted IS NOT NULL ";
            } else {
                $clause .= $where . " s.deleted IS NULL ";
            }
        }

        if (isset($searchFiltered->previous) AND $searchFiltered->previous) {
            $where = ($where) ? " AND " : " WHERE ";
            $clause .= $where . " s.id < " . $searchFiltered->previous;
        }
        if (isset($searchFiltered->string) AND $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 's.id', $where);
                $clause .= SQL::searchSCG($searchFiltered->string, 's.title', ' OR ');
                $clause .= " ) ";
            }
        }

        if ($count) {
            $sqlInner = "SELECT count(s.id) as `count` FROM form_section s ";

            $statement = $connection->prepare($sqlInner);
            $statement->execute();
            return $queryResult = $statement->fetchColumn();
        }
//----------------------------------------------------------------------------------------------------------------------------------------------------
        $sql = "SELECT s.id FROM form_section s ";
        $sql .= $clause;

        if (isset($searchFiltered->ordr) AND Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) AND array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY " . $sortSQL[$columnNumber] . " $dir";
            }
        } else {
            $sql .= ' ORDER BY s.id DESC';
        }

        if ($startLimit !== NULL AND $endLimit !== NULL) {
            $sql .= " LIMIT " . $startLimit . ", " . $endLimit;
        }

        $statement = $connection->prepare($sql);
        $statement->execute();
        $filterResult = $statement->fetchAll();
        $result = array();

        foreach ($filterResult as $key => $r) {
            $result[] = $this->find($r['id']);
        }
//-----------------------------------------------------------------------------------------------------------------------
        return $result;
    }

}
